steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'southamerica-east1-docker.pkg.dev/youtubemp3-425921/youtubemp3/youtubemp3:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/youtubemp3-425921/youtubemp3/youtubemp3:latest']